Restore Python 3.7 compatibility by not using functools.cached_property.
collective/collective.glossary pull request #69
Opened 2023-12-14 10:06 UTC by mauritsvanrees

Note that Python 3.7 is end of life, and this add-on is not tested on it. But this was an easy fix.

2023-12-16 12:29 UTC, ksuess requested changes
Let's update `setup.py` with a `python_requires=">=3.8"` according the classifiers and that Python 3.7 has reached its end of life.

2023-12-18 09:14 UTC, mauritsvanrees commented
> Let's update `setup.py` with a `python_requires=">=3.8"` according the classifiers and that Python 3.7 has reached its end of life.

The problem I see with such a change, is that this makes it impossible to install this package on Python 3.7, even though it would actually work, after this PR anyway.

In core Plone I am inclined to use the classifiers for the versions that we recommend, and to keep `python_requires` more lenient.  For example, in `Products.CMFPlone` on branch 5.2.x, the [`setup.py`](https://github.com/plone/Products.CMFPlone/blob/5.2.x/setup.py) has classifiers only for Python 2.7 and 3.8, but `python_requires` still accepts Python 3.6 and 3.7.

But if you still prefer, I am happy to change it here.

In fact, I would be happy to drop Plone 5.2 support.

2023-12-18 09:33 UTC, ksuess commented
> > Let's update `setup.py` with a `python_requires=">=3.8"` according the classifiers and that Python 3.7 has reached its end of life.
> 
> The problem I see with such a change, is that this makes it impossible to install this package on Python 3.7, even though it would actually work, after this PR anyway.
> 
> In core Plone I am inclined to use the classifiers for the versions that we recommend, and to keep `python_requires` more lenient. For example, in `Products.CMFPlone` on branch 5.2.x, the [`setup.py`](https://github.com/plone/Products.CMFPlone/blob/5.2.x/setup.py) has classifiers only for Python 2.7 and 3.8, but `python_requires` still accepts Python 3.6 and 3.7.
> 
> But if you still prefer, I am happy to change it here.

Ah, OK, now I am aware that it in fact makes sense to use the classifiers for recommendations. But keep the range of required versions wider. Thanks for the hint. I retract my change request.

2023-12-18 09:34 UTC, ksuess commented
> In fact, I would be happy to drop Plone 5.2 support.

+1 from me.

2023-12-18 09:35 UTC, ksuess approved these changes

2023-12-19 15:31 UTC, merged